api_platform:
    title: SuDespacho API
    version: 1.0.0
    mapping:
        paths:
            - '%kernel.project_dir%/src/BackOffice/Products/Infrastructure/ApiPlatform/Resource/'
            - '%kernel.project_dir%/src/BackOffice/Users/Infrastructure/ApiPlatform/Resource/'
    formats:
        jsonld: ['application/ld+json']
        json: ['application/json']
    docs_formats:
        jsonld: ['application/ld+json']
        jsonopenapi: ['application/vnd.openapi+json']
        html: ['text/html']
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: true
    event_listeners_backward_compatibility_layer: false
    keep_legacy_inflector: false
    swagger:
        api_keys:
            access_token:
                name: Authorization
                type: header
